### ISSUE TITLE
Disable globbing for =

### ISSUE THREAD

**Issue by Necoro** [arzzen/calc.plugin.zsh#1]
In your examples, you have to quote an expression containing *, which is not so intuitive.

Solution: Set `noglob`: Insert after your function definition:
```zsh
aliases[=]='noglob ='
```

**Comment by arzzen** [comment]
Fixend in #2

**Comment by Necoro** [comment]
I just received [the hint from the zsh-devs](http://www.zsh.org/mla/users/2017/msg00578.html) that an alias '=' works, but is not expected to work (in all situations). I'll leave it in my personal setup, though.

**Comment by arzzen** [comment]
alias changed to "calc"
