### ISSUE TITLE
Use zcalc instead of bc

### ISSUE THREAD

**Issue by Necoro** [arzzen/calc.plugin.zsh#2]
Hi,

I just noticed, that ZSH already ships a calculator `zcalc` (see `man zshcontrib`) -- perhaps this could be used instead of `bc`?

I replaced your function by (cf #1)
```zsh
autoload -U zcalc
function = {
    zcalc -e "$*"
}
aliases[=]='noglob ='
```
Pros:

- no external program needed
- zcalc seems to support way more constructs than bc

**Comment by arzzen** [comment]
Thanks for your contribution @Necoro, I updated calc.plugin.zsh.
