### ISSUE TITLE
invalid alias '=' encountered while printing aliases

### ISSUE THREAD

**Issue by jhrcook** [arzzen/calc.plugin.zsh#6]
Hello,

I cloned the this repo to my `$ZSH_CUSTOM/plugins/` folder and changed the directory name to "calc". 

When I run `source /Users/admin/.oh-my-zsh/custom/plugins/calc/calc.plugin.zsh`, I am now able to use the plugin (which is awesome, by the way!). I have added this line to my `.zshrc`, but on the loading of my terminal (iTerm2), I get the following error and cannot run `= 2+2`.

```
/Users/admin/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh:31: invalid alias '=' encountered while printing aliases
```

However, if I then source the `calc.plugin.zsh` file manually (using the same command as above), I can then use the plugin.

Do you know how to fix this? I'm new to zsh and oh-my-zsh so I apologize if this is a newbie error. I am running macOS Mojave (v.10.14.4) on a 13" 2016 MacBook Pro.

Thank you,
\- Josh Cook

**Comment by NickkoG** [comment]
I use Antigen plugin manager and I get the same error.

**Comment by Dentrax** [comment]
Same error. @arzzen

**Comment by bqnguyen94** [comment]
Related: zsh-users/zsh-syntax-highlighting#526

**Comment by arzzen** [comment]
Hi, there is another alias instead of `= 2+2` , you can use `calc 2+2`

**Comment by JoshPaulie** [comment]
I had the same issue. Moving the calc plugin to be loaded last fixed it

**Comment by equationzhao** [comment]
> I had the same issue. Moving the calc plugin to be loaded last fixed it

That works 👍

**Comment by p1r473** [comment]
Sourcing this even as the last line in the file still doesnt fix it for me. Any other solutions? @Dentrax

**Comment by Dentrax** [comment]
Sorry @p1r473, I don't use this plugin anymore. (Don't use any alternative either)
